### ISSUE TITLE
PO File cant be renamed on Windows when it exists already

### ISSUE THREAD

**Issue by jjaun** [riccardoFasan/django-polyglot#4]
Error MEssage --> FileExistsError: [WinError 183] 

FIX:

**django-polyglot.py**
Line 92 & Line 93 --> use **os.replace** insted of **os.rename**

Since Python 3.3, there is now a standard cross-platform solution, [os.replace](https://docs.python.org/3/library/os.html#os.replace)

**Comment by riccardoFasan** [comment]
Hi, I made the fix and merged it. Thank you for the issue 😘!
